In [14]:
tinggi = [180, 215, 210, 210, 188, 176, 209, 200] # dalam cm 

# Import numpy dengan alias np
import numpy as np

# Buat numpy array dengan list tinggi beri nama variabel np_tinggi
np_tinggi = np.array(tinggi)



In [15]:
# Print tipe data np_baseball
np_tinggi

array([180, 215, 210, 210, 188, 176, 209, 200])

In [10]:
# Buat np_tinggi menjadi dalam satuan meter
np_tinggi = np_tinggi / 100

# print np_tinggi
np_tinggi

array([0.018 , 0.0215, 0.021 , 0.021 , 0.0188, 0.0176, 0.0209, 0.02  ])

In [19]:
berat = [88.5, 100, 98, 101, 78.3, 65.3, 109, 110]

# Buatlah numpy array dari list berat dan simpan dalam np_berat
np_berat = np.array(berat)


# hitung bmi dari berat dan tinggi simpan ke dalam variabel bmi
bmi = np_berat / np_tinggi ** 2
bmi

array([0.00273148, 0.00216333, 0.00222222, 0.00229025, 0.00221537,
       0.00210808, 0.00249536, 0.00275   ])

In [35]:
# Buatalah numpy array boolean dengan denga operator > untuk mencari bmi yang lebih besar dari 23
np_bmi = bmi > 23

np_bmi


array([False, False, False, False, False, False, False, False])

In [36]:
# Simpan dalam variabel bmi_tinggi
bmi_tinggi = np_bmi

In [39]:
# Partisi numpy array bmi dengan menggunkan bmi_tinggi untuk mencari bmi yang hanya lebih besar dari 23
np_bmi = bmi_tinggi 
np_bmi = bmi > 23
np_bmi


array([False, False, False, False, False, False, False, False])

In [43]:
#B

In [49]:
# print hasil np_berat yang melik index terakhir
np_berat[7]




110.0

In [50]:
# print 5 elemen terakhir dari np_tinggi
np_tinggi[0:5]

array([180, 215, 210, 210, 188])

In [55]:
pemain_basket = [[180, 78.4],
                [215, 102.7],
                [210, 98.5],
                [188, 75.2]]

# Buatlah 2D array dari pemain_basket simpan dalam variabel basket_2d

basket_2d = np.array([[180, 78.4],[215, 102.7],[210, 98.5],[188, 75.2]])

# print tipe dari basket_2d
basket_2d


array([[180. ,  78.4],
       [215. , 102.7],
       [210. ,  98.5],
       [188. ,  75.2]])

In [56]:
# print basket_2d
print(basket_2d)


[[180.   78.4]
 [215.  102.7]
 [210.   98.5]
 [188.   75.2]]


In [57]:
# print dimensi dari basket_2d dengan basket_2d.shape
basket_2d.shape


(4, 2)

In [59]:
# Gunakan slicing untuk untuk mengambil hanya kolom pertama dari basket_2d

basket_2d[:,0:1]




array([[180.],
       [215.],
       [210.],
       [188.]])

In [66]:
# Gunakan slicing untuk mendapatkan 2 baris terakhir dan hanya kolom kedua dari basket_2d
basket_2d[2,:]


array([210. ,  98.5])

In [64]:
np_mat = np.array([[1, 2],
                   [3, 4],
                   [5, 6]])
print(np_mat * 2)
print(np_mat + np.array([10, 10]))
print(np_mat + np_mat)

[[ 2  4]
 [ 6  8]
 [10 12]]
[[11 12]
 [13 14]
 [15 16]]
[[ 2  4]
 [ 6  8]
 [10 12]]


In [81]:
# Print dengan tambahkan berat dari basket_2d (kolom kedua) dengan 5 
berat=(basket_2d + 5)
berat
# berat[2,:]
print (np_mat + berat[2,:])



[[216.  105.5]
 [218.  107.5]
 [220.  109.5]]


In [83]:
# Print dengan mengubah tinggi basket_2d (kolom pertama) yang awalnya satuannya cm menjadi m
tinggi=(basket_2d /100) 
tinggi 

array([[1.8  , 0.784],
       [2.15 , 1.027],
       [2.1  , 0.985],
       [1.88 , 0.752]])

In [84]:
# Berapakah mean dari np_tinggi? Kemudian print

np.mean(np_tinggi)



198.5

In [85]:
# Berapakah median dari np_tinggi? Kemudian print

np.median(np_tinggi)


204.5

In [ ]:
# Print tinggi dari basket_2d (kolom pertama)
rata_rata = ____
print("Rata - Rata: " + ____ )

# Print median dari tinggi basket_2d
med = ___
print("Median: " + ____)

# Print standar deviasi dari basket_2d
stddev = ____
print("Standard Deviation: " + ____)

# Print korelasi antara kolom pertama dengan kedua dari basket_2d
korelasi = _____
print("Korealasi: " + ___)